name: Cypress-Cucumber Tests
on:
    push:
        branches: [master]
jobs:
    Run_test:
        runs-on: ubuntu-20.04 # Choosing OS
        strategy:
            matrix:
                node-version: [14.17.0]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
            - name: update node manager
              run: npm i npm@latest
            - name: install all dependencies
              run: npm i
            - name: run test
              run: npx cypress run --config-file config/config.js
            - name: Generate reports
              if: always()
              run: npm run cypress:report
            - name: copy reports
              run: cp ./cucumber-messages.ndjson cucumber-report/
            - run: cp ./cucumber-report.html cucumber-report/
            - name: Upload artifact cucumber-report
              uses: actions/upload-artifact@v3
              if: always()
              with:
                  name: cucumber-report
                  path: ./cucumber-*.*
                  retention-days: 5 
            - name: Deploy report
              uses: JamesIves/github-pages-deploy-action@3.1.0
              if: always()
              with:
                  ACCESS_TOKEN: ${{'secrets.ACCESS_TOKEN'}}
                  BRANCH: master # The branch the action should deploy to.
                  FOLDER: cucumber-report # The folder the action should deploy.
                  TARGET_FOLDER: docs
